### PR TITLE
Apply appropriate casing to CommentThreadStatus property names

### LINKED ISSUE #439: Azure DevOps : exception deserializing comment thread
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.github.mc1arke.sonarqube.plugin.almclient.azuredevops.model.enums.CommentThreadStatus` from String "wontFix": not one of the values accepted for Enum class: [fixed, bydesign, active, wontfix, unknown, closed, pending]

### PR DESCRIPTION
**Pull request by jcuzzi**
Fixes #439

### CODE REVIEW

**Comment by mc1arke** [comment]
Is the correct fix for this not to update the `@JsonProperty` values in https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/master/src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/azuredevops/model/enums/CommentThreadStatus.java to match the values in https://docs.microsoft.com/en-us/javascript/api/azure-devops-extension-api/commentthreadstatus?

**Comment by jcuzzi** [comment]
Either way works.  I think this way makes it more fool proof, but it is up to you.

**Comment by mc1arke** [comment]
Part of the reason I'm suggesting changing the enum is that any serialised value produced by the service wont work after your change, since they wont match the possibly values supported by the API. We don't currently serialise these enum values so it's not currently causing an issue, but it's something we should fix in the right way if we can.

**Comment by mc1arke** [comment]
Merged, thanks for the quick turn-around on the fix.

**Pull request merged**
