### PR TITLE
Add deep links to PR decoration

### LINKED ISSUE #662: PR decoration links to icon SVG
**Describe the bug**
The (GitLab) PR decoration comment has each analysis icon wrapped with a hyperlink _that points to the icon SVG_.

I see how the list items are created at https://github.com/mc1arke/sonarqube-community-branch-plugin/blob/release/1_8/src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetails.java#L224-L236. However, I don't understand yet how the image ends up being wrapped by a link. `MarkdownFormatterFactory` and friends don't smuggle in elements, do they?

**Expected behavior**
Not sure...either no link at all or a link to respective metric e.g. https://my.sonar/component_measures?id=some-id&metric=new_coverage&pullRequest=42&view=list

**Screenshots**
Screen Shot 2022-08-24 at 16 59 55

**Software Versions**
 - SonarQube Version: 8.9.6
 - Plugin Version: 1.8 something

### PR DESCRIPTION
**Pull request by marcelstoer**
This adds deep links to the three issue types Bugs, Vulnerabilities, and Code Smells. Furthermore, it adds deep links to Coverage and Duplications.
The important changes are in [ReportGenerator.java](https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/792/files#diff-acc5158145bb98e81d62521f67cd91d38bc1ed6019fbe0424bfb04a8126470cf).

Fixes #662

### Preview
GitLab-SQ-decoration

### CODE REVIEW

**Comment by CristianDuta** [comment]
That would be helpful. We would definitely like to see this land in the next release.

**Comment by ExplodingSalad** [comment]
This feature would be quite handful for us as well. Is there any ETA for it?

**Comment by ttreuthardt** [comment]
Thanks a lot for the PR. This change would be great. Hope it can be integrated soon.

**Comment by marcelstoer** [comment]
@mc1arke looks like this fix would be welcome by the community. Any chance this will make it into the next release?

**Comment by mc1arke** [comment]
Merged, thanks for the contribution!

**Comment by marcelstoer** [comment]
Thanks for merging. Any chance this will be available in the next release that is _not_ yet targeting SQ 10 (e.g. 1.14.1 maybe)?

**Pull request merged**
