### PR TITLE
Patching the 1.14.0 version of the plugin with a bugfix

### PR DESCRIPTION
**Pull request by rafaelissaomiyagawa**
Patching 1.14.X with #738: Missing PR data

      More details in:
        https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/847/files

      - Bumping the version to 1.14.1
      - This commit is based on tag 1.14.0

### CODE REVIEW

**Comment by rafaelissaomiyagawa** [comment]
Sorry, I did not find any specific branch to create a PR for 1.14.0 version of the plugin. 

We did some testing and the patch applied resolves the problem described in #738.
We use this plugins with the Sonarqube 9.9.1 LTS in production.

**Comment by mc1arke** [comment]
Closing as abandoned given the PR has never merged cleanly and hasn't been fixed.

**Comment by afteroot** [comment]
So sadly ((

**Comment by dkeitzel** [comment]
Thank you for this. We'll use this as well for our LTS installation.

**Pull request closed without merging**
