### PR TITLE
Fix Bitbucket PR reports in Sonarqube 8.9.9 LTS

### PR DESCRIPTION
**Pull request by LennartKroes**
Commit 2d5d2e5d724dd8ed177e720dda8bf2702f656cdf in the master branch fixed an issue that is also an issue in the 1.8 branch. So therefore this PR for the 1.8 branch.

Original PR #586
Courtesy of @jochim-vd 

Would fix issue #636 and #644

_Recreated the PR as the checks on the previous PR (#645) were bugged due to initial incorrect PR branch targeting._

### CODE REVIEW

**Comment by arturzielinskicard** [comment]
Can someone accept this PR and merge it?

**Comment by DmitryKubahov** [comment]
Looking forward to this fix. Please, check it.

**Comment by macskay** [comment]
Still waiting for this fix. Appreciate it very much!

**Comment by macskay** [comment]
I created a fork this repo , applied the changes from @LennartKroes and created a temporary release, until @mc1arke merged this one into the main repository since it was business critical for us. Please be aware, that this Release will only stay alive until the official fix is merged.

**Comment by mc1arke** [comment]
Closing since the original change was cherry-picked during normal backporting operations

**Pull request closed without merging**
