### PR TITLE
#77:  Approve PR that passed quality gate (Bitbucket Server)

### LINKED ISSUE #77: Approve PR that passed quality gate
This feature will allow to configure the PR to make it required to pass the quality gate. It is only necessary to add a comment user to the required reviewers.

### PR DESCRIPTION
**Pull request by artemy-osipov**
A parameter has been added that allows to approve Pull Request that passed quality gate. If new changes are made and the quality gate no longer passes then approve is removed.

resolve #77 for Bitbucket Server

### CODE REVIEW

**Comment by marvin-w** [comment]
I think this breaks all my changes xD

https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/105

dayum.

**Comment by artemy-osipov** [comment]
@marvin-w Bitbucket Server and Bitbucket Cloud have incompatible API which requires a separate implementation of the PR decoration so I think the only conflict will be the name of the package.

**Comment by mc1arke** [comment]
@artemy-osipov are you still interested in getting this merged? There have been quite a few changes in the Bitbucket implementation so this has conflicts which prevent me reviewing it properly and/or merging.

**Comment by artemy-osipov** [comment]
Decorating PR for Bitbucket Server was migrated to Code Inside that has the functionality to restrict PR to merge. So it is no longer necessary to approve PR

**Comment by nfalco79** [comment]
It could be anyway a confgurable option. We had implemented in our pipeline with curl and wait to get the analisysId. If it was already included in the plugin since it has the bitbucket Bitbucket/GitHub/Lab authentication was 10000 better.

**Pull request closed without merging**
