### PR TITLE
#782: Add support for Sonarqube 10.1

### PR DESCRIPTION
**Pull request by mc1arke**
Updates to the Sonarqube APIs for version 10.1

### CODE REVIEW

**Comment by markri** [comment]
Not sure how this works as there is a hardcoded version of sonarqube embedded, so please consider to also support the latest sonarqube version (which is 10.2 atm)

**Comment by hballangan-mdsol** [comment]
> Not sure how this works as there is a hardcoded version of sonarqube embedded, but please consider to also support the latest version (which is 10.2 atm)

I'm guessing there will be a separate PR for 10.2

**Review by felipefalcao-iclinic — APPROVED** [review]

**Comment by alessandro-cerasino** [comment]
Hello, could you merge/release this PR please?

**Comment by alessandro-cerasino** [comment]
@mc1arke Hi :), is thre any reason why this PR is not merged?
Thanks

**Comment by byronestebancndt** [comment]
Hey there, is this PR going to work for Sonarqube 10.3?

**Comment by PaulAshraf** [comment]
Is this gonna fix the issues on 10.3 #829 ?

**Comment by cizara** [comment]
Hi, I've been running Sonarqube 10.1 with the artifact from bluebu (https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/786) since 7th September whitout any issues. Will this PR be merged?

**Comment by miks** [comment]
@mc1arke new release this year?

**Pull request merged**
