### PR TITLE
Implement bitbucket cloud PR decoration

### PR DESCRIPTION
**Pull request by marvin-w**
This PR aims to provide the ability to use the pull request decoration feature for bitbucket cloud.

Things that have to be done in the PR:

- [x] Bitbucket Server implementation is moved to dedicated `server` package.
- [x] API is analysed.
- [x] DTO objects are defined.
- [x] Bitbucket Cloud implementation is added.
- [x] Deletion of comments works.
- [x] Post summary works.
- [x] Diff based comments work.
- [x] Documentation is up to date.

### CODE REVIEW

**Comment by mc1arke** [comment]
Do Bitbucket Server and Cloud share a common API through the likes of their Code Insights feature?

**Comment by marvin-w** [comment]
The code insights API is o my available in bitbucket Server. In general the cloud and the on prem solution don't share the same API which is quite unfortunate.

**Comment by mc1arke** [comment]
Be aware that Sonarqube 8.1 has a limited list of decorators it supports, Bitbucket is included, but I'm not sure if the configuration options that the UI passes will provide everything you need for auth. It's worth having a look at what the sq-8_1-support branch contains to see how your change would fit in there, and consider that you'd effectively have to drive logic about using BitBucket Server or Bitbucket cloud from a single Bitbucket entry point, with it using logic (probably from the configured Bitbucket domain name) about which decorator to use

**Comment by marvin-w** [comment]
Hm yea I just checked it out. Only Bitbucket Server is supported. It probably won't work with the cloud version then.

They will probably write a paid app for it.

I'd still like to make this feature available in 7.9 - as that's the LTS version.

**Comment by marvin-w** [comment]
@mc1arke I've used the DefaultMarkdownFormatter.

Is this how it is supposed to look like?

image

**Comment by marvin-w** [comment]
@mc1arke I think I'm done with this. Feel free to review when you get some spare time.

**Comment by singhsoldier13** [comment]
Thanks for implementing this. We are testing this PR on our Sonarqube 7.9 instance and it is successfully commenting on PRs.
However, it is not deleting previous comment. Confirmed that "Enable deleting comments" option is "On" for both projects and globally.

**Comment by marvin-w** [comment]
Thanks for the feedback. I'll recheck but it worked for me the last time and I thought I haven't changed anything.

Any errors in the log?

**Comment by marvin-w** [comment]
I just rechecked. It still works for me locally. Can you verify that the User UUID is correct?

**Comment by singhsoldier13** [comment]
@marvin-w Thanks for quick reply. We jus debugged and found out that uuid was incorrect.
It is provided in format {uuid} but were using uuid without "{", "}".
It is working now!! Thanks so much

**Comment by singhsoldier13** [comment]
> @mc1arke I've used the DefaultMarkdownFormatter.
> 
> Is this how it is supposed to look like?
> 
> image
> 
> okay nevermind. It should look like this.
> 
> image

On New bitbucket PR experience, we can see the spacing issue in html:
image

On the old PR view, it is displaying fine:
image

**Comment by marvin-w** [comment]
Filed a bug for that already. Atlassian is investigating.

**Comment by singhsoldier13** [comment]
> Filed a bug for that already. Atlassian is investigating.
> 
> Do you also love this great new experience ;-).

Oh yes,, really like it

**Comment by jburgel-davinci** [comment]
Does someone has some example of parameters that has to be used and how in order to make this work? I tried various examples but seem to not get the comments working - but branch analysis is correctly displayed in sonar ( version 7.9.2 ) .
For example if url to my bitbucket repository would be bitbucket.org/company_workspace/projectname/src/master would workspace and repository slug be correct? ( I have removed some values that we do actually use and put some dummy ones there ) 

$SONAR_MAVEN_GOAL
-Pbuild-server,production,distribute,installer --batch-mode --errors
-Dcom.github.mc1arke.sonarqube.plugin.branch.pullrequest.bitbucket.cloud.appUsername=user@company.test
-Dcom.github.mc1arke.sonarqube.plugin.branch.pullrequest.bitbucket.cloud.appPassword=passwordvalue
-Dcom.github.mc1arke.sonarqube.plugin.branch.pullrequest.bitbucket.cloud.userUuid={useruuid}
-Dcom.github.mc1arke.sonarqube.plugin.branch.pullrequest.bitbucket.cloud.workspace=company_workspace
-Dcom.github.mc1arke.sonarqube.plugin.branch.pullrequest.bitbucket.cloud.repositorySlug=projectname
-Dsonar.pullrequest.branch=$GIT_BRANCH
-Dsonar.pullrequest.key=$PullRequestId
-Dsonar.pullrequest.base=master
-Dsonar.host.url=...
-Dsonar.login=...
-Dsonar.java.libraries=target

**Comment by jburgel-davinci** [comment]
I thought I made a mistake by typing parameters manually in Jenkins job, but I noticed they can be configured per project and not globally in settings in sonar so that was my confusion. After correct setup it works as expected! Great job!

**Comment by marvin-w** [comment]
@mc1arke did you have time to check this already? Are there still things unclear? Can we help somehow? 

I'd really like to see this one merged.

**Comment by marvin-w** [comment]
@singhsoldier13 / @jburgel-davinci  Is any of you using the new "Reports" feature within Bitbucket Cloud?

**Comment by Roberdvs** [comment]
Thank you very much for this PR!

I was able to make the Bitbucket Cloud PR decorations work by configuring the settings directly in the SonarQube project page and then running in Jenkins something like:
```
sonar-scanner -Dsonar.pullrequest.branch=${env.CHANGE_BRANCH} \
-Dsonar.pullrequest.base=${env.CHANGE_TARGET} \
-Dsonar.pullrequest.key=${env.CHANGE_ID}
```

Is there a way to provide the other settings when running the scan or configure some of them at the global level like with the other providers? In order to avoid having to configure projects one by one inside SonarQube.  

This doesn't seem to work:

```
sonar-scanner -Dcom.github.mc1arke.sonarqube.plugin.branch.pullrequest.bitbucket.cloud.appUsername=$username \
-Dcom.github.mc1arke.sonarqube.plugin.branch.pullrequest.bitbucket.cloud.appPassword=$pass \
-Dcom.github.mc1arke.sonarqube.plugin.branch.pullrequest.bitbucket.cloud.userUuid=$uuid \
-Dcom.github.mc1arke.sonarqube.plugin.branch.pullrequest.bitbucket.cloud.workspace=$workspace \
-Dcom.github.mc1arke.sonarqube.plugin.branch.pullrequest.bitbucket.cloud.repositorySlug=$repoName \
-Dsonar.pullrequest.branch=${env.CHANGE_BRANCH} \
-Dsonar.pullrequest.base=${env.CHANGE_TARGET} \
-Dsonar.pullrequest.key=${env.CHANGE_ID}
```

since I'm getting `java.lang.IllegalStateException: com.github.mc1arke.sonarqube.plugin.branch.pullrequest.bitbucket.cloud.workspace must be specified in the project configuration` in the logs.

Ideally I would just configure everything but the repoSlug at SonarQube global settings and then provide the repoSlug when running the scan.

Thanks!

**Comment by yeroc** [comment]
@mc1arke Is this being considered for merging?  We're interested in a solution to publish PR comments to BitBucket Cloud and it looks like this would be perfect.

**Comment by parinapatel** [comment]
@mc1arke  Do we have ETA on this PR ? I am excited about this one.

**Comment by marvin-w** [comment]
I like that this PR is getting attention again. However, I'm personally reconsidering the approach I took when implementing it. Since a month or so Bitbucket Cloud has also launched it's code insight's feature - which personally would feel much better than using comments. That's why I'm currently thinking about dropping this PR and creating one for code insight's ( unfortunately the APIs for cloud and server differ a lot ).

https://confluence.atlassian.com/bitbucket/code-insights-994316785.html

There's a big but to this: I don't want to waste my time for something great again only for it to rotten in a branch without it being considered for merging.

Therefore, @mc1arke would you mind providing feedback on this subject?

**Comment by mc1arke** [comment]
@marvin-w I'm more that happy to merge a feature if it is useful. Given your branch conflicts with its target, I've left the PR alone. I'm about to merge in the Sonarqube 8.1 features, then Sonarqube 8.2, both of which restrict the available decoration settings, so you'll want to make sure that you'll be able to work within those restrictions, and perform any logic in the current Bitbucket decorator to decide whether you're working with Bitbucket server or Bitbucket.com, and delegate to the relevant decorator.

**Comment by marvin-w** [comment]
Closed in favor of #182.

**Pull request closed without merging**
