### PR TITLE
Add support for decorating Pull Requests (proxy for TFS)

### PR DESCRIPTION
**Pull request by akonit**
Inspired by https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/31, this plugin sends issues to external service (determined by configurable url). My initial purpose was to communicate with remote .net service posting comments to TFS pull requests - so there is no communication with TFS itself, only preprocessing and proxy call. Just thought it might be useful to somebody with a similar task.

### CODE REVIEW

**Comment by bambuca** [comment]
Hi @akonit , do you plan to resolve conflicts and complete this PR? If not, I can try to do so...

**Comment by akonit** [comment]
> Hi @akonit , do you plan to resolve conflicts and complete this PR? If not, I can try to do so...

Hi @bambuca. I resolved conflicts

**Comment by mc1arke** [comment]
Closing this since there's been no progress on it in over 6 months and it isn't compatible with the target branch. If you'd like to proceed with it then please open an MR targeting the appropriate branch and with the above comments resolved.

**Comment by NorDroN** [comment]
What about this PR?

**Comment by mc1arke** [comment]
@NorDroN I'm not sure i understand your question. See my last comment on the PR about the steps required if this PR is still required.

**Pull request closed without merging**
