### PR TITLE
Resolve summary comment on GitLab MRs when the Quality Gate has passed

### PR DESCRIPTION
**Pull request by teake**
MRs where the Quality Gate passes do not a priori need additional action.
Hence the summary comment can be resolved automatically by SonarQube.

### CODE REVIEW

**Comment by yzhoholiev** [comment]
Hi! We have a similar modification in our fork. It would be great to make it part of the plugin.

**Review by mc1arke — CHANGES_REQUESTED** [review]
Hi @teake.

Thanks for the contribution and sorry for the delayed review. Could you add a test to ensure your new code is covered please? I need to ensure that any code can be quickly verified during any future changes without me having to exhaustively test multiple manual combinations.

Thanks!

**Comment by teake** [comment]
@mc1arke Done -- at least, I suspect so. I haven't run locally with coverage to check if it now is more than 80% but I guess this should do the trick.

**Comment by adpeyre** [comment]
@mc1arke Is it possible to merge this pull request. 
The behavior is annoying because Sonarqube comment is deleted but the thread is still present.

image

**Review by mc1arke — APPROVED** [review]

**Comment by mc1arke** [comment]
@adpeyre your issue is something different: you're seeing threads created from inline code-comments where an entry still exists where the thread used to be, whereas this is the summary comment thread being changed here which isn't an in-line comment.

**Comment by mc1arke** [comment]
Merged. Thanks for the contribution!

**Pull request merged**
