### PR TITLE
Update to SonarQube 10.6

### PR DESCRIPTION
**Pull request by phoval**
`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'java.net.FactoryURLClassLoader@6441c486-com.github.mc1arke.sonarqube.plugin.scanner.CommunityProjectBranchesLoader': Resolution of declared constructors on bean Class [com.github.mc1arke.sonarqube.plugin.scanner.CommunityProjectBranchesLoader] from ClassLoader [java.net.FactoryURLClassLoader@6441c486] failed; nested exception is java.lang.NoClassDefFoundError: org/sonar/scanner/bootstrap/ScannerWsClient`

### CODE REVIEW

**Comment by atalakey4work** [comment]
Dears,

Can someone please merge this PR?

Regards,

**Comment by gjabouley-invn** [comment]
Hello

please see https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/904
This is probably not the only change to make 10.6 properly supported, you would at bare minimum need the change in above PR

Also i would recommend against updating the README about the compatibility table, there is already a PR dedicated https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/906/files , and in the end this is the responsibility of the maintainer to properly version its plugin. Probably 1.19 will go for 10.4, 1.20 for 10.5 and 1.21 for 10.6...

**Comment by phoval** [comment]
@gjabouley-inv: #904 do nothing more than upgrade SonarQube version, which is already included in the current PR.
The Readme should be updated in the PR, otherwise it will become outdated, like it is currently.
The Maintainer can force-push the PR to update the versioning.

**Comment by gjabouley-invn** [comment]
@mc1arke could you please approve the workflow, so at least we have a build artefact available from the GitHub checks that users can use for deployment?

> @gjabouley-invn: #904 do nothing more than upgrade SonarQube version, which is already included in the current PR. The Readme should be updated in the PR, otherwise it will become outdated, like it is currently. The Maintainer can force-push the PR to update the versioning. Jar is available for testing : https://github.com/phoval/sonarqube-community-branch-plugin/releases/tag/1.19.1

My point is, as in the linked PR, a 10.5 incompatibility was detected not at init (which makes the issue easy to spot) but rather when configuring a specific feature of the plugin (creating a new DevOps platform integration). This highlight that usages can vary from one setup to another, and even if for your use case the 10.6 works maybe for others with another setup (another ALM, ...) there could still be some other issues to fix.
So it is important for the maintainer to gather user feedbacks for a little while before being confident enough to say "10.6 support is ok".
First thing now it to get the plugin built with GitHub Actions, so people can get a snapshot version from this PR and test it.

About the versioning, well outdated or wrong, both mean incorrect to me 😃

**Comment by pedrocarrico** [comment]
Just installed @phoval 's release and everything seems to be working.

**Comment by PeteMac88** [comment]
@mc1arke Any update here?

**Comment by bobowang2017** [comment]
> @gjabouley-invn: #904 do nothing more than upgrade SonarQube version, which is already included in the current PR. The Readme should be updated in the PR, otherwise it will become outdated, like it is currently. The Maintainer can force-push the PR to update the versioning. Jar is available for testing : https://github.com/phoval/sonarqube-community-branch-plugin/releases/tag/1.19.1

https://github.com/phoval/sonarqube-community-branch-plugin/releases/tag/1.19.1
this works , good

**Comment by anotherandi** [comment]
Hi @mc1arke ,

i tested the "1.19.1" version of phoval in various combinations with SonarQube 10.6.

Tested Sarif import and code coverage.
In SonarQube the analysis of branches and PR worked and showed corerct results.
The PR/MR decoration and summary worked in GitLab and Github.
Tested with sonar-scanner 5.0.1 and 6.1.

Also tested with the current development head of sonarqube (upcoming 10.7)

Could also see the errors mentioned by mohamedazaddou and grandeon after update to 10.6 from 10.4.
But could solve them by deleting <project-dir>/.scannerwork and ~/.sonar.

@mc1arke Could you please approve the proposed changes of this PR and release a 1.20 or 1.21 for SonarQube 10.6?

Thank you for your great work!

**Comment by j-martin** [comment]
I also confirm that this PR is working great on 10.6 (installed with the official Helm chart, if it matters).

**Pull request merged**
