### PR TITLE
Fix adding discussions for gitlab

### PR DESCRIPTION
**Pull request by uwej711**
Hi, 

thanks for this great plugin. I did some tests decorating merge request with our gitlab server and had to change this to make it work.

1. always get the commits regardless of deleteCommentsEnabled (otherwise no discussion is created below)
2. add old_path when adding the discussion (otherwise the comment is not displayed inline in the diff in gitlab)

Kind regards,
Uwe

### CODE REVIEW

**Comment by tisoft** [comment]
Hi,

>     1. always get the commits regardless of deleteCommentsEnabled (otherwise no discussion is created below)
Thanks, that is clearly a bug!

>     2. add old_path when adding the discussion (otherwise the comment is not displayed inline in the diff in gitlab)
In my tests this was not necessary. I will try to debug when the old_path is really necessary.

**Comment by uwej711** [comment]
I tried this with changes to an existing file and by adding a new file and I needed old_path in both cases, on a self hosted Gitlab FOSS 12.6.2.

Without it the comments where not directly visible in the diff. Sometimes they showed up when running another analysis with new commits on the same merge request but they never showed up there on the first analysis. This might also be a gitlab issue.

**Comment by mc1arke** [comment]
@tisoft Did you get a chance to investigate the second point reported in this change?

**Comment by tisoft** [comment]
Not yet. Will do it this week.

**Comment by kortov** [comment]
related to #86

**Comment by mc1arke** [comment]
Merged. Thanks for the contribution.

**Pull request merged**
