### PR TITLE
SonarQube 10.5 compatibility

### PR DESCRIPTION
**Pull request by dkeitzel**
As far as I know this should be enough to produce a binary compatible plugin for SonarQube 10.5. See also https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/900#issuecomment-2075860129.

### CODE REVIEW

**Comment by mc1arke** [comment]
This change isn't actually required: we only need the Sonarqube build dependency to allow us to compile the plugin. Given 10.5 hasn't changed any of the APIs we use then there's nothing that we need to change; I just need to push docker images and update the README

**Comment by tburschka** [comment]
Any news on this?

**Comment by zisuu** [comment]
would be nice to get this solved soon. We're currently having people that can't change some settings in their Projects due to this. Thanks a lot for your efforts 👍

**Comment by gjabouley-invn** [comment]
Hello
as usual for people in a hurry, SNAPSHOT version built from this PR can be downloaded using GitHub checks artefacts: https://github.com/mc1arke/sonarqube-community-branch-plugin/actions/runs/8969366962/artifacts/1476415257

**Comment by gjabouley-invn** [comment]
> > Are you sure? I'm by no means an expert in Java binary compatibility 😅. But at least the return type of `ProjectAlmSettingDao#insertOrUpdate` [changed](https://github.com/SonarSource/sonarqube/commit/99bf48a4107238ade798c32b9a0e17b196d16c90#diff-3081029d09c0a8ac2a5a1ac358813bcb9b7949bd9308824510edafbc4c327209R50).
> 
> Sorry, I'd missed that change, and yes it will cause problems for anyone creating a new ALM setting. This means we'll need to create a release purely for 10.5 😞

You will probably need to build a new version for each new version of SQ, why not aligning the plugin version number with SQ version ? ;)

**Comment by benoit-waldmann** [comment]
Any news on this? @mc1arke

**Comment by FelixReuter** [comment]
Since this PR still is open: By now SQ has released at least one newer build of 10.5: 10.5.1.90531

**Comment by gjabouley-invn** [comment]
There shall not be any issue with new SQ 10.5 release.
This plugin depends on API, and those are never modified for bugfixes releases. So at first sight no need update the SQ  dependency version.

**Comment by apetrelli** [comment]
I hope @mc1arke is ok... Probably he just lost the enthusiasm to maintain this project.

**Comment by mc1arke** [comment]
> I hope @mc1arke is ok... Probably he just lost the enthusiasm to maintain this project.

I'm ok, and haven't lost enthusiasm, just capacity to be able to perform testing of releases for now

**Comment by zisuu** [comment]
Hello, fyi we decided to try the snapshot version of 1.19.1. As far as we can say from user experience, it seems to work without any new issues, and we are again capable of editing the sonar project configs 👍  thanks a lot.

**Comment by a-mnich** [comment]
Hi, we are also using the snapshot productively for about a month now. No issues so far.

**Comment by gjabouley-invn** [comment]
@mc1arke seems that this PR contains the only small change necessary to make the plugin compatible with 10.5, can you merge and go for a 1.10 ?

**Comment by adrianmusante** [comment]
I built the Docker image [adrianmusante/sonarqube:10.5](https://hub.docker.com/r/adrianmusante/sonarqube) which already has the plugin pre-configured, hopefully it will be of use to someone.

**Comment by florianmutter** [comment]
Any updates here?

**Comment by ummarbhutta** [comment]
When this PR will be merged?

**Comment by this-is-tobi** [comment]
Thanks for the merge @mc1arke, is there a release planned ?

**Comment by Asmabagwan1** [comment]
@mc1arke We have recently upgrade our SonarQube from 7.8 to 10.5 successfully.
We are facing issue with branch analysis. We have installed community branch plugin for this with version 1.22.0, but this plugin after installation is not reflecting on web UI. I have done all the configurations mentioned here https://github.com/mc1arke/sonarqube-community-branch-plugin in manual installation.

Please help us resolve this issue

**Pull request merged**
