### PR TITLE
Azure devops api version

### PR DESCRIPTION
**Pull request by jbaehr-phoenis**
Adds an option to configure the api version of azure devops.
This was prviously not possible and would lead to problems/errors.
This should also fix the problem in issue #290 .

### CODE REVIEW

**Comment by mc1arke** [comment]
Thanks for your suggested contribution. As the Azure DevOps decorator has been significantly overhauled since the issue that you've linked to was raised, can you confirm the scenario where you’re still encountering problems please? I'm generally against adding user-interface options for configuring the Pull Request decorators since they don't then sit alongside the main decorator configuration options so cause a poor user experience, so would like to understand the issue being resolved here.

**Comment by dhaas-phoenis** [comment]
Our Azure DevOps Server 2020 (on-premise) does not accept api requests with api-version=4.1. That is why we added this option. I understand why you are against adding this user-interface option. What would be a better solution?

See attached file:
[sonarqube_ce.log](https://github.com/mc1arke/sonarqube-community-branch-plugin/files/7126065/sonarqube_ce.log)

**Comment by mc1arke** [comment]
It's odd that 2020 is giving the response you've provided, as the v4 API has existed since 2018 - https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rest-api-versioning?view=azure-devops#supported-versions. Can you confirm if your server is generally up-to-date with latest patches?

I wonder whether the use of 4.1 rather than 4.0 is causing any issues, and also whether pinning to 3.1 would provide a wider range of support across all versions of Azure Devops currently available.

**Comment by dhaas-phoenis** [comment]
Yes, I can confirm. We use the latest available patches. It's Azure DevOps Server 2020 Update 1.1.

Not every API needs the "-preview"-flag. But the Pull Request Statuses API does. No matter which version I use. Tested from 3.0 to 6.1. Every version needs it. But Azure DevOps Services (cloud) only needs the preview flag for api-version 6.1. Seems to be something on-premise specific.

Should we cancel this PR and create an issue instead?! We can still use our own forked version that works for us until this is fixed.

**Comment by mc1arke** [comment]
Thanks for the confirmation. I'd agree that the fix for this is slightly different from your proposed change since it requires using a preview version for a few selected endpoint calls rather than allowing configuring a version for all endpoint calls. Could you therefore raise an issue - or an alternative PR - to cover this, and close this PR?

**Pull request closed without merging**
