### PR TITLE
Gitlab MR Decorator: Add encoding of Message

### PR DESCRIPTION
**Pull request by sfaqer**

### CODE REVIEW

**Comment by mc1arke** [comment]
Is this causing something to break? I'm trying to understand why this is targeting the 8.1 release rather than master

**Comment by sfaqer** [comment]
@mc1arke Change base to master.

**Comment by mc1arke** [comment]
@sfaqer Can you provide a summary of why this change is needed? I'm struggling to work out the issue from your commit message

**Comment by sfaqer** [comment]
@mc1arke fixing this for Cyrillic messages. 

IMG_20200528_071848_081

**Comment by mc1arke** [comment]
Merged. Thanks for the contribution!

**Pull request merged**
