### PR TITLE
If duplication and issues equal zero, to do repost "notes" instead "discussions" in GitLab

### LINKED ISSUE #106: Summary comment must be resolved by a hand before pull request could be merged.
Summary comment must be resolved by a hand before pull request could be merged. So now pull request decoration at least in gitlab negatively affects a merge process when pull request couldn't be merged automatically after successful completion of a pipeline.

1. Navigate to your gitlab project’s settings page, select the **Only allow merge requests to be merged if all threads are resolved** check box and hit Save for the changes to take effect.
2. Make merge request without issues and click a button "Merge when pipeline succeeds"

**Expected behavior**
Pull request should be automatically merged.

**Screenshots**
Screenshot 2020-02-26 at 14 06 47

Screenshot 2020-02-26 at 14 13 34

Screenshot 2020-02-26 at 13 55 20

**Software Versions**
 - Gitlab
 - SonarQube Version: 7.9.2 (build 30863)
 - Plugin Version: 1.2.1-RC3

**Suggestion**
I think that it will be good to resolve summary comment thread automatically if there are no issues found.

### PR DESCRIPTION
**Pull request by Grintek**
If duplication and issues equal zero, to do repost "notes" instead "discussions" in GitLab fixes #106

### CODE REVIEW

**Comment by mareksimunek** [comment]
@mc1arke Could you please take a look?  We are facing similar issue and this seems that it will resolve our troubles.

**Comment by chinhodado** [comment]
Can this be reviewed and merged in? It would be really helpful. Thanks.

**Comment by mc1arke** [comment]
Whilst I'm generally happy with this change, it needs to be rebased against the current master branch as the conflicts currently prevent merge.

**Comment by mareksimunek** [comment]
@Grintek will you rebase please? or should I do it?

**Comment by mc1arke** [comment]
@Grintek are you interested in carrying this change forward?

**Comment by MCMicS** [comment]
Why closed. This seems to be a good PR

**Pull request closed without merging**
