### PR TITLE
Sq 8 3 support

### PR DESCRIPTION
**Pull request by arch1tect0r**
Hello!

I found that this branch can be used with latest SonarQube version. 

And also I found that it can't work with MR from forks. I made some modifications. What do you think about this?

### CODE REVIEW

**Comment by mc1arke** [comment]
Please separate out any unrelated commits.

Given the Sonarqube 8.3 version bump isn't needed, committing that change prevents backwards compatibility so I'd prefer it wasn't included.

For the Gitlab change, could you ensure it's covered by a test, and that you're not breaking any existing functionality?

Please also ensure you're following the commit message format for this repository: https://github.com/RomuloOliveira/commit-messages-guide

**Comment by arch1tect0r** [comment]
I see that I brake some tests =) I'll check it later.

It works in my productions. So I think all will be fine.

**Comment by shouldnotappearcalm** [comment]
@arch1tect0r Can your 8.3 plug-in release a jar? Let's download and test it

**Comment by mc1arke** [comment]
@shouldnotappearcalm apart from the Gitlab change, this plugin is identical to the 8.2 branch, which you can download an artifact for from the Artifcats link on https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/156/checks?check_run_id=747257134

**Comment by shouldnotappearcalm** [comment]
@mc1arke Does it support version 8.3.1?

**Comment by mc1arke** [comment]
I've not explicitly checked, but the changes between 8.3.0 and 8.3.1 don't seem to be likely to break branch management

**Comment by shouldnotappearcalm** [comment]
Can the 1.4.0 version officially release a jar package? I have some problems with local compilation

**Comment by mc1arke** [comment]
I'm sorting out the recent changes which are preventing the release running, then will get 1.4.0 officially released, however it only support 8.1. You'll need 1.5.0 to support 8.2, which I'll release very soon after 1.4.0 if everything goes to plan

**Comment by shouldnotappearcalm** [comment]
So where can I download plugins that can be tested and used on 8.3, because my local gradle compilation has always failed, thank you very much

**Comment by shouldnotappearcalm** [comment]
I have downloaded the plugin from your submission, thanks a lot

**Comment by mc1arke** [comment]
I'm closing this since it's trying to do too many things under a single change. Please raise a separate MR with individual changes if you want to carry any of these changes forward.

**Comment by donkeylin** [comment]
Hi, just wanted to know how's the gitlab fork MR decoration going, I see this issue is closed, is there any MR to trace that?

**Pull request closed without merging**
